name: Publish conda

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  make:
    uses: ScottMudge/FreeCADMakeImage/.github/workflows/bundle.yaml@master
    with:
      ref: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.ANACONDA_TOKEN }}
