name: Publish conda

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

jobs:
  make:
    uses: https://raw.githubusercontent.com/scottmudge/FreeCADMakeImage/master/.github/workflows/bundle.yaml
    with:
      ref: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.ANACONDA_TOKEN }}
