name: Publish snap

on:
  push:
    tags:
      - "*" # build for any new tag (on all branches)
    
  workflow_dispatch:

jobs:
  publish:
    uses: realthunder/FreeCADMakeImage/.github/workflows/snap.yaml@master
    with:
      ref: ${{ github.ref_name }}
    secrets:
      token: ${{ secrets.STORE_LOGIN }}
